### ISSUE TITLE
Test failure in test_model.py

### ISSUE THREAD

**Issue by mhucka** [GillesPy2/GillesPy2#219] opened 2019-09-02 23:37 UTC
When I ran the unit tests, there was a failure in `test_ode_propensity` in `test/test_mode.py`. The error was:
```
FAIL: test_ode_propensity (test_model.TestModel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mhucka/project-files/stochss/repos/GillesPy2/test/test_model.py", line 151, in test_ode_propensity
    self.assertEqual(model.listOfReactions['r3'].ode_propensity_function, 'rate*A*B')
AssertionError: 'rate*B*A' != 'rate*A*B'
- rate*B*A
?       --
+ rate*A*B
?      ++
```

The problem was due to the way that propensity formulas were sorted in `Reaction.sanitized_propensity_function(...)`. PR #218 implements a fix for this.

**Comment by seanebum** [comment] 2019-09-11 17:03
PR #218 has been merged, I ran the tests a few times and have not received this error (however, this error didn't really come up for me before, I'd assume it's rather intermittent). I'm going to go ahead and close the issue, since the merged changes should logically prevent this from happening again, and I have been unable to reproduce the error after merging.

**Closed by seanebum** 2019-09-11 17:03 UTC
