### ISSUE TITLE
anyway to dynamically change an affinity rate? during a simulation

### ISSUE THREAD

**Issue by akmadamanchi** [GillesPy2/GillesPy2#406] opened 2020-07-14 00:08 UTC
Hi, 

I'm trying to run a simulation in which i dynamically change one of the rates.   They way i have typically done this is to run a simulation for 1 second and then use the endpoints as the initial values in a subsequent 1 second simulation.  In the python 2 version of gillespy this worked fairly well. 

Now it takes 8 seconds to launch the model each time so it takes prohibitively to use this method. Is there any way to either speed up the launch of the model or any built-in for dynamically changing some of the affinity rates?

**Comment by seanebum** [comment] 2020-07-14 17:53
Hey akmadamanchi,

Yes there should be some ways that this can be done.  Just to get some more details, are you using a specific solver?  Also, are you intending to change the parameter continuously or discretely?  If you are looking to do this discretely, you can use the VariableSSACSolver for the best results like this:


```
solver=VariableSSACSolver(model)  
results = model.run(solver=solver, t=10)  
for i in range(20, 210, 10):  
    results = model.run(solver=solver, t=i, resume=results, variables={'rate1':i*.0001})
```

The Resume feature lets you pass the previous results in, and the variables feature lets you adjust the parameter value without re-compiling. Though in testing this, it appears there is currently a bug causing the VariableSSACSolver to recompile each call when using the resume feature.  I will work on getting a fix for this and it should perform very quickly.

**Comment by akmadamanchi** [comment] 2020-07-14 18:07
Hi,

Write now I am using from gillespy2.solvers.cpp.ssa_c_solver import SSACSolver

Regarding the parameter: I am trying to model a system in which the amount of ligand is continously rising. I have modeled ligand binding as a pseudo first order reaction, and ligand levels are captured within the binding affinity. We're doing it this way because we don't want any noise introduced at this stage.

I think the resume function you're suggesting sounds ideal. Thank you.

**Comment by seanebum** [comment] 2020-07-23 15:10
Hello,

Just to follow up, GillesPy2 has now been updated with some bugfixes, and the variable c solver should no longer require recompilation between calls.  The above code should run much faster now.

**Comment by hemanshudas** [comment] 2020-07-27 17:54
HI @seanebum ,

Will the method work with TauLeapingSolver with multiple trajectories?

**Comment by seanebum** [comment] 2020-07-27 19:04
This method should also work with the TauLeapingSolver, however instead of passing the variables keyword argument, you would need to update the model directly each step through the loop using something like `model.listOfParameters['rate1'].expression=new_value`

**Comment by hemanshudas** [comment] 2020-07-28 07:00
I can't seem to make it work. I don't think the parameter value gets changed.

It's the same code I shared on the TauHybridSolver thread. 
```
results_001 = model1.run(solver=TauLeapingSolver(), show_labels=True, seed=10, live_output = 'progress', t=200)
model1.listOfParameters['mu_v'].expression='0'
results_002 = model1.run(solver=TauLeapingSolver(), show_labels=True, seed=10, live_output = 'progress', t=240, resume= results_001)
```

**Comment by seanebum** [comment] 2020-07-29 15:29
That is interesting... Changing values was not the original intention of the resume feature, but it seems like a reasonable use-case for it.  I'll take a look and see why it's not picking up the new values in this solver.

**Comment by hemanshudas** [comment] 2020-08-01 14:57
Hi @seanebum,
Did you have a chance to look at the resume feature and updating the parameter in between?

**Comment by seanebum** [comment] 2020-08-03 18:46
Hey @hemanshudas ,

I have not gotten to this yet, but I will definitely take a look at this today or tomorrow and let you know!

**Comment by seanebum** [comment] 2020-08-03 21:40
Hello @hemanshudas,

I looked into this and have figured out what is going on here... because the the parameter expression has already been evaluated to a numeric value, that numeric value is being retained, even though you giving it a new expression.  

In the line where you are settting the expression:
`model1.listOfParameters['mu_v'].expression='0'`

instead of setting the "expression" attribute directly, try using the set_expression() method:
`model1.listOfParameters['mu_v'].set_expression('0')`

Try setting the new parameters this way, and it should work as intended!

**Comment by hemanshudas** [comment] 2020-08-04 06:51
Yes. This works. Thanks a ton.

Would you know any clear drawbacks of using this method rather than using events along with TauHybridSolver (when the events are time-dependent).

For me, this is way faster than using the TauHybridSolver, and I'm inclined to go this route to solve my model.

**Comment by seanebum** [comment] 2020-08-04 13:59
The only major drawback that I can think of is that this changes the model throughout the simulation, rather than the model containing all of the necessary information to reproduce the experiment (i.e. if you print the model at the end of simulation, the parameter values will reflect the last used values, not the original ones, and there will be nothing indicating how the model has changed or is meant to change throughout the simulation).  Events would also allow for some additional features, such as allowing for other trigger conditions (non-time-dependent),  delayed assignments, or assignments to species populations directly (rather than parameters).

**Closed** 2020-08-19 15:34 UTC
