### ISSUE TITLE
Having a model with random initial species number and using num_trajectories>1 at the same time?

### ISSUE THREAD

**Issue by dom-linkevicius** [GillesPy2/GillesPy2#369] opened 2020-06-05 16:36 UTC
First of all, many thanks for a very useful package!

I had a question regarding whether it is possible to have a model with a random variable for a species initial_value? Essentially I have a model where I know the equilibrium distribution and can sample it, but I want to model a perturbation. The idea is to draw an initial value of a species from the equilibrium distribution and use the perturbed model to get the resulting time series. Is this at all possible? 

I tried using the event functionality with BasicTauHybridSolver, but the resulting model due to the solver and having to simulate something I don't really need to is much too slow for my uses.

**Comment by briandrawert** [comment] 2020-06-05 18:11
This is a duplicate of #359 

It is not possible to change the initial condition of a model object once instantiated.  However, you can efficiently instantiate model object in a loop and give each of them different initial conditions:
```
solver = VariableSSACSolver(model=model)
result = model.run(solver=solver, variables={'A': np.random.poisson(20)})
for i in range(1,10):
    result += model.run(solver=solver, variables={'A': np.random.poisson(20)})
result.plotplotly()
```

See #359 for more details

**Closed by briandrawert** 2020-06-05 18:11 UTC
