### ISSUE TITLE
Exception handling: Adding a duplicate [Species, Parameter, Reaction] should raise Error specific to that entity

### ISSUE THREAD

**Issue by georgemhall** [GillesPy2/GillesPy2#61] opened 2019-02-06 01:56 UTC
I noticed this while fixing some broken unit tests...

For example, in gillespy2/core/gillespy2.py:
```
def problem_with_name(self, name):
        [...]
        if name in self.listOfParameters:
            return ModelError('Name "{}" is unavailable. A parameter with that name exists.'.format(name))
```
According to gillespyError.py, we have specific exceptions - SpeciesError, ReactionError, ParameterError, etc

I make a motion that in a future release, we utilize those for more robust error reporting.

**Comment by Thisisnotdalton** [comment] 2019-02-08 02:57
I am all for more robust error reporting, but I am not sure how we would go about classifying some of these errors. At the time, I used a generic ModelError because I was not sure whether the issue would be a ParameterError or SpeciesError.

For instance, if a model has a Parameter named "A" and we try to add a Species with the same name of "A", would the Parameter be at fault or the Species? Individually, both the Parameter and Species are valid and could be added to a Model, but the problem is that we are adding both of them to the same Model. We could make the code more specific to raise a ParameterError when adding a Parameter and a SpeciesError when adding a Species, but the problem_with_name function was made more general to ensure that both Species and Parameters adhered to the same name constraints within that specific Model.

Maybe a more robust solution would be to create an ModelNameError separate from the SpeciesError and ParameterError for handling cases where the Species/Parameter is otherwise alright but its name is unavailable in the given Model.

**Comment by briandrawert** [comment] 2019-03-19 13:57
Added #88, closed this issue

**Closed by briandrawert** 2019-03-19 13:57 UTC
Labels: enhancement, question
